### ISSUE TITLE
Error: watch EMFILE 

### ISSUE THREAD

**Issue by jkin8010** [zhex/fe-dev-server#4]
livereload watch node_modules 
```js
{ Error: watch src/main/webapp/node_modules/whet.extend/li
b/whet.extend.js ENFILE
    at exports._errnoException (util.js:1022:11)
    at FSWatcher.start (fs.js:1305:19)
    at Object.fs.watch (fs.js:1330:11)
    at createFsWatchInstance (src/main/webapp/node_modules
/chokidar/lib/nodefs-handler.js:37:15)

    at setFsWatchListener (src/main/webapp/node_modules/ch
okidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (src/main/
webapp/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleFile (src/main/webap
p/node_modules/chokidar/lib/nodefs-handler.js:255:21)
    at FSWatcher.<anonymous> (src/main/webapp/node_modules
/chokidar/lib/nodefs-handler.js:473:21)
    at FSReqWrap.oncomplete (fs.js:111:15)
  code: 'ENFILE',
  errno: 'ENFILE',
  syscall: 'watch src/main/webapp/node_modules/whet.extend
/lib/whet.extend.js',
  filename: 'src/main/webapp/node_modules/whet.extend/lib/
whet.extend.js' }
```

**Comment by zhex** [comment]
Hi, jkin8010

Normally the livereload server only watch the public folder, mock folder and view folder. Could you give   out your fdsconfig settings?

**Comment by jkin8010** [comment]
basePath included 'node_modules'

```js
module.exports = {
    basePath: __dirname,
    viewFolder: '.',
    publicFolder: '.',
    mockFolder: '.',
    routeFile: 'routes.js',
    mockExts: ['.mock', '.json'],
    port: 3000,
    enableJava: true
};
```

**Comment by zhex** [comment]
Thank you for your issue.

Please update the package to v1.6.0, the new version excludes node_modules by default. Also `livereload` prop in fds-config could be a **livereload option object** other than a boolean value.
